apiVersion: v1
entries:
  vault-secrets-operator:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-03-21T06:44:37.364157913Z"
    description: A Helm chart for Kubernetes
    digest: 897aeca0a684dc6b10428dd9c8236c35561baffb00940a4a88407bcc1424f2e8
    name: vault-secrets-operator
    type: application
    urls:
    - vault-secrets-operator-0.1.0.tgz
    version: 0.1.0
generated: "2025-03-21T06:44:37.363500817Z"
