apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:k8s-practice-annam/k8s-cluster-creation.git
    targetRevision: HEAD
    path: sample-manifests 
  destination:
    server: https://kubernetes.default.svc
    namespace: test-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true

