apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-svc
  name: demo-svc
spec:
  ports:
  - name: node
    port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: demo-svc
  type: NodePort
